### ISSUE TITLE
win 10 环境：UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 97: illegal multibyte sequence

### ISSUE THREAD

**Issue by XMuli** [liudaolunboluo/WxChatRecordTool#2]
### Thanks
感谢楼主的轮子，体验了一把

### env
- win10 21H2
- Python 3.9.6
- pip 21.1.3

### ERROR
报了错误 ：
```python
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 97: illegal multibyte sequence
```

### Try Modify
尝试修改了 `with open(message_path, 'r') as content_j:`  为 `with open(message_path, 'rb') as content_j:` 后，又会出现其它问题

```python
Traceback (most recent call last):
  File "D:\projects\WxChatRecordTool\ChatRecordWorldCloud.py", line 32, in <module>
    load_dict = json.load(content_j)
  File "C:\Users\xmuli\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 97: illegal multibyte sequence
```

### Need Help
~~前端脚本不会很会修改~~  

### update
google 了一下可以实测成功生成了，已提交 PR；

**Comment by liudaolunboluo** [comment]
因为没有windows环境所以windows测试不充分，不好意思，非常感谢您的pr
