### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by zhowan** [liudaolunboluo/WxChatRecordTool#4]
Traceback (most recent call last):
  File "WxAnnualRecords.py", line 117, in <module>
    len(from_user_list), list(date_count_map)[0][0], list(date_count_map)[0][1], late_record[0],
IndexError: tuple index out of range

查了一下，是 late_record 为空，但是我的聊天记录是有凌晨 00:00 到 06:00 之间的，记录没有添加到 late_record 里面。

**Comment by liudaolunboluo** [comment]
> Traceback (most recent call last): File "WxAnnualRecords.py", line 117, in len(from_user_list), list(date_count_map)[0][0], list(date_count_map)[0][1], late_record[0], IndexError: tuple index out of range
> 
> 查了一下，是 late_record 为空，但是我的聊天记录是有凌晨 00:00 到 06:00 之间的，记录没有添加到 late_record 里面。

刚刚处理了下，如果没有0点到6点到数据那么就取0点之前最晚的记录，这样不会报错了，但是你这个数据为啥没有添加到0到6之间的可以debug一下，可以在https://github.com/liudaolunboluo/WxChatRecordTool/blob/df9dadffbfe314892e820fe39e8627b7a730db86/annual_records/WxAnnualRecords.py#L109 
这一行打断点看看为啥没有进这个if
